//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealTimeVoiceRecognizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp")]
        public string TempFolder {
            get {
                return ((string)(this["TempFolder"]));
            }
            set {
                this["TempFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Russian (Russia)")]
        public string SelectedCulture {
            get {
                return ((string)(this["SelectedCulture"]));
            }
            set {
                this["SelectedCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>en-AU,English (Australia)</string>\r\n  <string>en-CA,English (Canada)</stri" +
            "ng>\r\n  <string>en-GB,English (United Kingdom)</string>\r\n  <string>en-IN,English " +
            "(India)</string>\r\n  <string>en-NZ,English (New Zealand)</string>\r\n  <string>en-U" +
            "S,English (United States)</string>\r\n  <string>en-ZA,English (South Africa)</stri" +
            "ng>\r\n  <string>af-ZA,Afrikaans (South Africa)</string>\r\n  <string>ar-AE,Arabic (" +
            "U.A.E.)</string>\r\n  <string>ar-BH,Arabic (Bahrain)</string>\r\n  <string>ar-DZ,Ara" +
            "bic (Algeria)</string>\r\n  <string>ar-EG,Arabic (Egypt)</string>\r\n  <string>ar-IQ" +
            ",Arabic (Iraq)</string>\r\n  <string>ar-JO,Arabic (Jordan)</string>\r\n  <string>ar-" +
            "KW,Arabic (Kuwait)</string>\r\n  <string>ar-LB,Arabic (Lebanon)</string>\r\n  <strin" +
            "g>ar-LY,Arabic (Libya)</string>\r\n  <string>ar-MA,Arabic (Morocco)</string>\r\n  <s" +
            "tring>ar-OM,Arabic (Oman)</string>\r\n  <string>ar-QA,Arabic (Qatar)</string>\r\n  <" +
            "string>ar-SA,Arabic (Saudi Arabia)</string>\r\n  <string>ar-SY,Arabic (Syria)</str" +
            "ing>\r\n  <string>ar-TN,Arabic (Tunisia)</string>\r\n  <string>ar-YE,Arabic (Yemen)<" +
            "/string>\r\n  <string>cs-CZ,Czech (Czech Republic)</string>\r\n  <string>nl-BE,Dutch" +
            " (Belgium)</string>\r\n  <string>fr-FR,French (France)</string>\r\n  <string>de-DE,G" +
            "erman (Germany)</string>\r\n  <string>it-IT,Italian (Italy)</string>\r\n  <string>id" +
            "-ID,Indonesian (Indonesia)</string>\r\n  <string>ja-JP,Japanese (Japan)</string>\r\n" +
            "  <string>ko-KR,Korean (Korea)</string>\r\n  <string>zh-CN,Chinese (Simplified)</s" +
            "tring>\r\n  <string>zh-TW,Chinese (Traditional, Taiwan)</string>\r\n  <string>ms-MY," +
            "Malay (Malaysia)</string>\r\n  <string>pl-PL,Polish (Poland)</string>\r\n  <string>p" +
            "t-BR,Portuguese (Brazil)</string>\r\n  <string>es-AR,Spanish (Argentina)</string>\r" +
            "\n  <string>es-BO,Spanish (Bolivia)</string>\r\n  <string>es-CL,Spanish (Chile)</st" +
            "ring>\r\n  <string>es-CO,Spanish (Colombia)</string>\r\n  <string>es-CR,Spanish (Cos" +
            "ta Rica)</string>\r\n  <string>es-DO,Spanish (Dominican Republic)</string>\r\n  <str" +
            "ing>es-EC,Spanish (Ecuador)</string>\r\n  <string>es-GT,Spanish (Guatemala)</strin" +
            "g>\r\n  <string>es-HN,Spanish (Honduras)</string>\r\n  <string>es-MX,Spanish (Mexico" +
            ")</string>\r\n  <string>es-NI,Spanish (Nicaragua)</string>\r\n  <string>es-PA,Spanis" +
            "h (Panama)</string>\r\n  <string>es-PE,Spanish (Peru)</string>\r\n  <string>es-PR,Sp" +
            "anish (Puerto Rico)</string>\r\n  <string>es-PY,Spanish (Paraguay)</string>\r\n  <st" +
            "ring>es-SV,Spanish (El Salvador)</string>\r\n  <string>es-US,Spanish (United State" +
            "s)</string>\r\n  <string>es-UY,Spanish (Uruguay)</string>\r\n  <string>es-VE,Spanish" +
            " (Bolivarian Republic of Venezuela)</string>\r\n  <string>ru-RU,Russian (Russia)</" +
            "string>\r\n  <string>tr-TR,Turkish (Turkey)</string>\r\n  <string>zu-ZA,isiZulu (Sou" +
            "th Africa)</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SupportedCultures {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SupportedCultures"]));
            }
            set {
                this["SupportedCultures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticallySaveText {
            get {
                return ((bool)(this["AutomaticallySaveText"]));
            }
            set {
                this["AutomaticallySaveText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Temp\\default.txt")]
        public string DefaultLogFile {
            get {
                return ((string)(this["DefaultLogFile"]));
            }
            set {
                this["DefaultLogFile"] = value;
            }
        }
    }
}
